**EX 1 /
MATRIX MULIPLICATION USING NUMPY**

In [5]:
import numpy as np
a=np.array([[1,2],[2,3]])
b=np.array([[2,5],[6,9]])
c=np.dot(a,b)
print(c)

[[14 23]
 [22 37]]


**"dot" which is used for matrix multiplication.**

In [6]:
import numpy as np
a=np.array([[1,2],[2,3]])
b=np.array([[2,5],[6,9]])
c=a*b
print(c)

[[ 2 10]
 [12 27]]


**using * operator element-wise multiplication, not matrix multiplication**

In [7]:
import numpy as np
a=np.array([[1,2],[2,3]])
b=np.array([[2,5],[6,9]])
c=a@b
print(c)

[[14 23]
 [22 37]]


**Instead of using dot operator for matrix multiplication**

**EX 2 / EIGEN DECOMPOSTION**

In [9]:
a=np.array([[4,2],[1,3]])
eigenvalues,eigenvectors=np.linalg.eig(a)
print("a")
print(a)
print("eigenvalues")
print(eigenvalues)
print("eigenvectors")
print(eigenvectors)

a
[[4 2]
 [1 3]]
eigenvalues
[5. 2.]
eigenvectors
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


**# EIGENDECOMPOSITION**

In [16]:
a=np.array([[3,5],[4,2]])
eigenvalues,eigenvectors=np.linalg.eig(a)

D=print(eigenvalues)
V=print(eigenvectors)
V_inv=np.linalg.inv(V)
print("eigen decomposition")



[[ 7. -2.]]
[[[ 0.78086881 -0.70710678]
  [ 0.62469505  0.70710678]]]


In [17]:

a = np.array([[3, 5],
              [4, 2]])

eigenvalues, eigenvectors = np.linalg.eig(a)

# Create diagonal matrix from eigenvalues
D = np.diag(eigenvalues)

# Inverse of the eigenvector matrix
V = eigenvectors
V_inv = np.linalg.inv(V)

# Reconstruct the original matrix using eigen decomposition
a_reconstructed = V @ D @ V_inv


print("Eigenvalues:")
print(eigenvalues)

print("Eigenvectors:")
print(eigenvectors)

print("Reconstructed matrix from eigen decomposition:")
print(a_reconstructed)


Eigenvalues:
[ 7. -2.]
Eigenvectors:
[[ 0.78086881 -0.70710678]
 [ 0.62469505  0.70710678]]
Reconstructed matrix from eigen decomposition:
[[3. 5.]
 [4. 2.]]


**finding eigen values,eigen vectors for eigen decomposition**

**EX 3 / SINGULAR VALUE DECOMPOSTION (SVD)**

In [22]:
a=np.array([[3,2,2],[2,3,-2]])
U,S,V=np.linalg.svd(a)
print("original matrix:")
print(a)
print("left singular vector:")
print(U)
print("singular values :")
print(S)
print("right singular value :")
print(V)

original matrix:
[[ 3  2  2]
 [ 2  3 -2]]
left singular vector:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
singular values :
[5. 3.]
right singular value :
[[ 7.07106781e-01  7.07106781e-01  3.67439059e-16]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


**EX 4 / DETERMINANT CALCULATION**

In [23]:
a=np.array([[6,1],[2,3]])
det=np.linalg.det(a)
print("original matrix:",a)
print("determinant of a:",det)

original matrix: [[6 1]
 [2 3]]
determinant of a: 15.999999999999998


**NORM CALCULATION**

In [24]:
v=np.array([3,4])
L1_norm=np.linalg.norm(v,ord=1)
L2_norm=np.linalg.norm(v)
print("vector v:",v)
print("L1 norm of v:",L1_norm)
print("L2 norm of v:",L2_norm)

vector v: [3 4]
L1 norm of v: 7.0
L2 norm of v: 5.0


**vector v is the original , 
L1 norm of v is the 3+4=7 ,
L2 norm of v is the square root of, 3+4 =5**